# Generated by Django 5.2.4 on 2025-07-10 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titel')),
                ('poster', models.ImageField(upload_to='event_posters/', verbose_name='Affisch')),
                ('short_description', models.CharField(max_length=300, verbose_name='Kort beskrivning')),
                ('description', models.TextField(verbose_name='Beskrivning')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Pris')),
                ('location', models.CharField(max_length=255, verbose_name='Plats')),
                ('slug', models.SlugField(blank=True, help_text='sökväg i webbläsaren (kan lämnas tom)', unique=True, verbose_name='Slug')),
                ('published', models.BooleanField(default=True, help_text='Markera om objektet ska vara publicerat', verbose_name='Publicerad')),
            ],
            options={
                'verbose_name': 'Evenemang',
                'verbose_name_plural': 'Evenemang',
            },
        ),
        migrations.CreateModel(
            name='EventDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(verbose_name='Datum och tid')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='events.event', verbose_name='Evenemang')),
            ],
            options={
                'verbose_name': 'Datum',
                'verbose_name_plural': 'Datum',
            },
        ),
        migrations.CreateModel(
            name='EventMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Bild'), ('video', 'Video')], max_length=10, verbose_name='Media-typ')),
                ('file', models.FileField(upload_to='event_media/', verbose_name='Fil')),
                ('caption', models.CharField(blank=True, max_length=255, null=True, verbose_name='Bildtext')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='events.event', verbose_name='Evenemang')),
            ],
            options={
                'verbose_name': 'Media',
                'verbose_name_plural': 'Medier',
            },
        ),
    ]
