# Generated by Django 5.2.4 on 2025-07-11 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='seats',
            field=models.IntegerField(default=1, verbose_name='Antal platser'),
            preserve_default=False,
        ),
    ]
