# Generated by Django 5.2.4 on 2025-07-03 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_event_end_date_remove_event_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(default='grona-hissen'),
            preserve_default=False,
        ),
    ]
