# Generated by Django 5.2.4 on 2025-07-12 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_location_alter_event_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Plats'),
        ),
        migrations.AlterField(
            model_name='event',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Pris'),
        ),
        migrations.AlterField(
            model_name='event',
            name='seats',
            field=models.IntegerField(blank=True, default=0, help_text='Detta är totala antalet platser som går att boka på hemsidan. Vuxen platser + (eventuelt) barn platser', verbose_name='Antal platser'),
        ),
    ]
