# Generated by Django 5.2.4 on 2025-07-12 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_location_alter_event_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='can_book',
            field=models.BooleanField(blank=True, default=True, help_text='Om man ska kunna boka plats på detta evenemang bocka i mig', verbose_name='Går att boka'),
            preserve_default=False,
        ),
    ]
