# Generated by Django 5.2.4 on 2025-10-01 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_can_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='salver_link',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='seats',
            field=models.IntegerField(blank=True, default=0, help_text='Detta är totala antalet platser som går att boka på hemsidan', verbose_name='Antal platser per datum'),
        ),
    ]
