# Generated by Django 5.2.4 on 2025-10-01 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_salver_link_alter_event_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='salver_link',
            field=models.CharField(blank=True),
        ),
    ]
