# Generated by Django 5.2.4 on 2025-10-02 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_event_salver_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='can_book',
            field=models.BooleanField(blank=True, help_text='Hemsidans innbygda boknings system', verbose_name='Går att boka'),
        ),
        migrations.AlterField(
            model_name='event',
            name='salver_link',
            field=models.CharField(blank=True, verbose_name='Salver länk (biljätter)'),
        ),
    ]
