# Generated by Django 5.2.4 on 2026-01-20 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_event_can_book_alter_event_salver_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdate',
            name='year_only',
            field=models.BooleanField(default=False, verbose_name='Endast år'),
        ),
        migrations.AlterField(
            model_name='eventdate',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Datum och tid'),
        ),
    ]
