version: "3.8"

services:
  backend:
    build: ./
    volumes:
      - ./:/app
      - static_volume:/app/static
    expose:
      - 8000

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - static_volume:/static
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend

volumes:
  static_volume:
