version: "3.8"

services:
  backend:
    build: ./
    volumes:
      - ./:/app
      - static_volume:/app/staticfiles
    expose:
      - 8000
  # cron to remove unverified bookings
  cron:
    build: ./
    volumes:
      - ./:/app
      - static_volume:/app/staticfiles
    command: ["sh", "-c", "cron && tail -f /var/log/cron.log"]
    depends_on:
      - backend

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - static_volume:/static
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend

volumes:
  static_volume:
