# Generated by Django 5.2.4 on 2025-10-02 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(verbose_name='Url till sidan')),
                ('main_text', models.TextField(verbose_name='Övertext')),
            ],
            options={
                'verbose_name': 'Sida',
                'verbose_name_plural': 'Sidor',
            },
        ),
    ]
