# Generated by Django 5.2.4 on 2025-10-02 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(verbose_name='Titel')),
                ('name', models.CharField(verbose_name='Namn')),
                ('phone', models.CharField(blank=True, verbose_name='Telefon')),
                ('email', models.CharField(blank=True, verbose_name='Email')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='Profil bild')),
            ],
        ),
    ]
