# Generated by Django 5.2.4 on 2025-10-02 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactuser',
            options={'verbose_name': 'Kontakt', 'verbose_name_plural': 'Kontakter'},
        ),
        migrations.AddField(
            model_name='contactuser',
            name='published',
            field=models.BooleanField(default=True, verbose_name='Publicerad'),
        ),
        migrations.AlterField(
            model_name='contactuser',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Profilbild'),
        ),
    ]
