# Generated by Django 5.2.4 on 2025-07-11 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
