# Generated by Django 5.2.4 on 2025-07-11 13:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_verified'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name': 'Bokning', 'verbose_name_plural': 'Bokningar'},
        ),
        migrations.AlterField(
            model_name='booking',
            name='adult_seats',
            field=models.PositiveIntegerField(default=0, verbose_name='Vuxen platser'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_number',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Boknings nummer'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='child_seats',
            field=models.PositiveIntegerField(default=0, verbose_name='Barn platser'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Namn'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='Verifierad'),
        ),
    ]
