# Generated by Django 5.2.4 on 2025-07-12 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_options_alter_booking_adult_seats_and_more'),
        ('events', '0004_alter_event_location_alter_event_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_date',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='events.eventdate'),
            preserve_default=False,
        ),
    ]
